markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM

comments :
   provider: disqus
   disqus:
     short_name:  boyudiao

name: Boyu's blog
description: Diaoboyu Blog and Homepage
url: http://ictdby.github.com
