markdown: kramdown
kramdown:
  input: GFM

comments :
   provider: disqus
   disqus:
     short_name:  joearmstrongsblog

name: Boyu's blog
description: Diaoboyu Blog and Homepage
url: http://ictdby.github.com
